### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by johnpena** [clintecker/python-googleanalytics#1]
I get the following error whenever I try to access an account where I'm not an administrator: `GoogleAnalyticsClientError: GAError: HTTP Error 401: Unauthorized`. No problems when I am the administrator for the account. Does this API only work when I'm an administrator?

**Comment by clintecker** [comment]
It shouldn't have any effect.  How are you providing your credentials to the api? Can you paste in any relevant bits of code you're using (obsfucating any personal information like username and passwords, of course).

**Comment by johnpena** [comment]
I'm using basically the same code in your usage example.

```
from googleanalytics import Connection
c = Connection('myaccount@gmail.com', 'mypassword')
c.get_accounts()
---------------------------------------------------------------------------
GoogleAnalyticsClientError                Traceback (most recent call last)

/Users/jcp20/development <ipython console> in <module>()

/Library/Python/2.6/site-packages/python_googleanalytics-1.0.2-py2.6.egg/googleanalytics/connection.pyc in get_accounts(self, start_index, max_results)
     40             data['max-results'] = max_results
     41         data = urllib.urlencode(data)
---> 42         response = self.make_request('GET', path, data=data)
     43         raw_xml = response.read()
     44         xml_tree = ElementTree.fromstring(raw_xml)

/Library/Python/2.6/site-packages/python_googleanalytics-1.0.2-py2.6.egg/googleanalytics/connection.pyc in make_request(self, method, path, headers, data)
    107         try:
    108             response = urllib2.urlopen(request)
    109         except urllib2.HTTPError, e:
--> 110             raise GoogleAnalyticsClientError(e)
    111         return response

GoogleAnalyticsClientError: GAError: HTTP Error 401: Unauthorized
```

**Comment by jsma** [comment]
Sorry to ask the obvious questions:

1) Are you sure you are providing credentials for a valid Google Account?
2) Are you sure this account has at least been given User privileges (aka "View reports only") and has at least 1 web profile selected in the Google Analytics admin interface?

I just tested this with another Google Account of mine and `connection.get_accounts()` worked as intended, pulling in only web profiles the account had been given explicit read access to.

**Comment by clintecker** [comment]
Yes I was going to ask the same question.  That error just means your credentials are incorrect as far as Google is concerned.

**Comment by johnpena** [comment]
Credentials are correct, I just tested this again. The user has been given privileges to view a profile in the admin interface. I'm guessing now that I might be seeing this error because the account is new (created in the last couple hours) and was just given user privileges. I'm going to test again in a few hours to see if this is the issue.
