### ISSUE TITLE
GoogleAnalyticsClientError: GAError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ghost** [clintecker/python-googleanalytics#8]
GoogleAnalyticsClientError: GAError: HTTP Error 403: Forbidden

**Comment by craigkerstiens** [comment]
Are you using a google apps account for a domain other than gmail? I'm able to access accounts with my @gmail.com address, but not with another domain.

**Comment by ollieglass** [comment]
Hi, I get the same error using a non-gmail address. Is this a known issue? Any chance of a fix?
